services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  Bam1to\AuditTrailBundle\:
    resource: "../src/"

  Bam1to\AuditTrailBundle\EventSubscriber\EntityAffectionSubscriber:
    tags:
      - { name: "doctrine.event_subscriber" }
